version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12vf400ulsbzx"
s3_prefix = "sam-app1"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"

